### ISSUE TITLE
Using with Electron

### ISSUE THREAD

**Issue by rimlin** [vicentedealencar/redux-pouchdb#2]
If i use redux-pouchdb in Electron, and after every starting app and adding new item to store see errors in console:
`Warning: flattenChildren(...): Encountered two children with the same key, `.0:$0`. Child keys must be unique; when two children share a key, only the first child will be used.`

And every time after adding new items in store and after restart app in console message `reduce this ..`  array of object growing together with error message `Warning: flattenChildren(...):` almost 2-fold and items in store alternate.

**Comment by vicentedealencar** [comment]
Hi, this warning came from react, you shold add a key prop on each element when passing an array as children.

The `reduce this` is logging every time an action is dispatched, then react triggers a rerender, and as there is still no keys the warning shows up again.

Looks like this issue is unrelated to this repo so I will close it, let me know if you still need help.
